//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTiki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlesComments
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentOn { get; set; }
        public Nullable<int> ArticalId { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Articals Articals { get; set; }
    }
}
