//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTiki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChiKH
    {
        public int MaDC { get; set; }
        public string TenKH { get; set; }
        public string DT { get; set; }
        public string TinhTP { get; set; }
        public string QuanHuyen { get; set; }
        public string PhuongXa { get; set; }
        public string DiaChi { get; set; }
        public string LoaiDC { get; set; }
    }
}
